### PR TITLE
Golangci lint actions

### LINKED ISSUE #36: actions/ci: run golangci-lint
This repo has a [golangci-lint configuration](https://github.com/grafeas/voucher/blob/main/.golangci.yml)

Let's run golangci-lint in Actions, so linting is checked automatically on incoming PRs. That will prevent regressions like https://github.com/grafeas/voucher/pull/32

Probably https://github.com/golangci/golangci-lint-action ?

### PR DESCRIPTION
**Pull request by thepwagner**
Enable golangci-lint in GitHub actions, so that formatting is verified in incoming PRs.

~When opened, I expect this PR to be rejected due to `auth.AuthError` - I'll address that after verifying it fails as expected 🤞 .~ This failure happened, as expected.

Closes https://github.com/grafeas/voucher/issues/36

### CODE REVIEW

**Review by rxbchen — APPROVED** [review]
Nice, enforcing lint is a good way to go 👍

File: v2/auth/error.go [hunk 1]
```diff
@@ -6,18 +6,18 @@ import (
 	"github.com/docker/distribution/reference"
 )
 
-// AuthError is the error returned when authenticating while pulling manifests connecting to protected systems
-type AuthError struct {
+// Error is the error returned when authenticating while pulling manifests connecting to protected systems
+type Error struct {
```
Comment (dani-santos-code) [inline v2/auth/error.go:10]: good catch!

**Review by dani-santos-code — APPROVED** [review]
